language: python
python:
  - "3.3.6"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls


# command to run tests
script:
  - py.test ./sdp_backend/test_GraphColouring.py

after_success:
  - coveralls

